keys:
  - &personal age1598sd2pa4l7qg9wwl56gj24d8npvntpq2h7a28lmva7mne5apa6s6pslvq
  - &host_xps age1tj8cqwlu4lg5qpd9kk7fxu9z705yrp0spuy94yslk0nq80kej3sqs534ce
creation_rules:
  - path_regex: secrets/xps\.yaml$
    key_groups:
    - age:
      - *host_xps
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *personal
