[config]
[config.custom_colors]
warning = "#D0A215"
success = "#879A39"

[templates.helix]
input_path = "~/.config/matugen/helix.toml"
output_path = "~/.config/helix/themes/matugen.toml"
post_hook = "pkill -USR1 hx"

[templates.pywalfox]
input_path = "~/.config/matugen/pywalfox.json"
output_path = "~/.cache/wal/colors.json"
post_hook = "pywalfox update"
